#!/bin/sh
PROJECTNAME=tradeequip-drv
DF=$(date --date 'now' +%Y%m%d)
mkdir -p rpm
cvs export -D20200101 $PROJECTNAME
cd $PROJECTNAME
cp $PROJECTNAME.spec $PROJECTNAME.spec.in
sed "/^Release: */ c\Release: alt0.cvs$DF" $PROJECTNAME.spec.in>$PROJECTNAME.spec;
rm -f $PROJECTNAME.spec.in
add_changelog -e "  - Automatic generated cvs build" $PROJECTNAME.spec;
make srpm 
mv rpm/*.src.rpm ../rpm
cd ..
rm -f -r $PROJECTNAME
#rpm --resign rpm/*
